spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
springdoc:
  version: '@project.version@'
